import { Grid2, List, ListItem, ListItemButton, Stack, Typography } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <Grid2 container>
            <Grid2 size={3}>
              <List disablePadding>
                <ListItem>
                  <Typography color="common.white" fontWeight="bold" variant="h4">
                    Pokemon
                  </Typography>
                </ListItem>
                <ListItemButton component={Link} sx={{ color: "common.white" }} href="/">
                  Home
                </ListItemButton>
                <ListItemButton component={Link} sx={{ color: "common.white" }} href="/pokemon">
                  Pokemon
                </ListItemButton>
                <ListItemButton component={Link} sx={{ color: "common.white" }} href="/create">
                  Create
                </ListItemButton>
              </List>
            </Grid2>
            <Grid2 height="100vh" p={8} size={9} sx={{ backgroundColor: "common.white" }}>
              <Stack alignItems="center" height="100%" spacing={2}>
                {children}
              </Stack>
            </Grid2>
          </Grid2>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
